### ISSUE TITLE
cann't locate libyajl on CentOS6

### ISSUE THREAD

**Issue by higkoo** [simplresty/ngx_mongo#4]
$ rpm -qa | grep yajl
yajl-1.0.7-3.el6.x86_64
yajl-devel-1.0.7-3.el6.x86_64

$ rpm -ql yajl yajl-devel
/usr/bin/json_reformat
/usr/bin/json_verify
/usr/lib64/libyajl.so.1
/usr/lib64/libyajl.so.1.0.7
/usr/share/doc/yajl-1.0.7
/usr/share/doc/yajl-1.0.7/COPYING
/usr/share/doc/yajl-1.0.7/ChangeLog
/usr/share/doc/yajl-1.0.7/README
/usr/share/doc/yajl-1.0.7/TODO
/usr/include/yajl
/usr/include/yajl/yajl_common.h
/usr/include/yajl/yajl_gen.h
/usr/include/yajl/yajl_parse.h
/usr/lib64/libyajl.so
/usr/share/doc/yajl-devel-1.0.7
/usr/share/doc/yajl-devel-1.0.7/COPYING

sudo ln -s /usr/include/ /usr/local/include/yajl
sudo ln -s /usr/lib64/ /usr/local/lib/libyajl.so.1
sudo ln -s /usr/lib64/ /usr/local/lib/libyajl.so.1.0.7
sudo ln -s /usr/lib64/ /usr/local/lib/libyajl.so

Still Cannot Find！

**Comment by lin1000** [comment]
update your /etc/ld.so.conf and add a new line that include the path to your libyajl.so (e.g. /usr/local/lib) , then rerun ldconfig to load the .so library. When that is completed, use ldconfig -p | grep yajl to verify the dynamic library have been loaded
